### PR TITLE
Down, way down

### PR DESCRIPTION
**Pull request by radiantly**
- [x] There is reasonable content on the page (see: [No Content](https://github.com/js-org/js.org/wiki/No-Content))
- [x] I have read and accepted the [Terms and Conditions](http://js.org/terms.html)

### CODE REVIEW

**Comment by MattIPv4** [comment]
@C0derLint This should really fail, the added lines should be before the bottom comment :)

**Comment by radiantly** [comment]
@MattIPv4 I'm not sure how exactly I can fail this one .. it follows all the rules :D - What do you think?

**Comment by MattIPv4** [comment]
@C0derLint Might just be easiest to move the comment to beyond the end of the object?

**Comment by radiantly** [comment]
@MattIPv4 Yeah, that makes more sense.

**Pull request closed without merging**
